### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by ext-beyondcente** [maokofan/portalSite_UI_vue#6]
大神你好，请问前端后台manage这边左边的可以收缩的菜单栏位，我用admin登入，但是不能通过ui界面去跳到其他页面添加测试内容，需要给admin添加额外的权限吗？

**Comment by ext-beyondcente** [comment]
Request URL: http://localhost:8888/api/back/sysModule/getCurrentUserRootModules
Request method: GET
Status code: 602 unknown
Remote address: 127.0.0.1:8888
Referrer policy: strict-origin-when-cross-origin



devServer: {
    host: '127.0.0.1',
    port: port,
    proxy: { // 设置代理
      '/api': {
          target: 'http://127.0.0.1:8289',
          // changeOrigin: true,
          pathRewrite: {
              "^/api" : ""
          }
      }
  },
    open: true,
    overlay: {
      warnings: false,
      errors: true
    },
}
这样配对吗？

**Comment by ext-beyondcente** [comment]
已经解决了

**Comment by maokofan** [comment]
好的
